name: Deploy Application Gateway

on:
  push:
    branches:
      - main

jobs:
  deploy-appgw:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy ARM template
        uses: azure/cli@v1
        with:
          inlineScript: az deployment group create --resource-group Siddhant --template-file armtemplates/appgw.json --parameters appGwName=myAppGateway location=eastus skuName=Standard_v2 capacity=2 vnetName=myVNet subnetName=appgw-subnet
